version: 2
updates:
  - package-ecosystem: npm
    directory: /apps/web
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      deck-gl:
        patterns:
          - "@deck.gl/*"
    ignore:
      - dependency-name: eslint
        versions:
          - ">=10.0.0"
    commit-message:
      prefix: deps

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    commit-message:
      prefix: ci
