"""Write the Homebrew formula from the signed release manifest (T194).

**Why Homebrew.** D058: a `.command` can never be notarised, a signed `.pkg`
needs the Apple Developer Program, and the curl one-liner is quarantine-free
only by an implementation detail Apple has never promised. Homebrew does not
quarantine what a *formula* installs, so nothing it puts on disk meets
Gatekeeper, and a tap needs no review. `brew install` becomes the durable Mac
route at no cost.

**Why the formula is thin.** It installs one thing: the release's own
`scripts/install.sh`, as the `throughline` command. That script is already the
launcher every other door wraps — install into `~/throughline-os` on first run,
start afterwards, offer an update when one is published — so the formula is a
fourth door onto one install sequence, not a second one. A formula that
unpacked the program into Homebrew's Cellar would have been a second copy that
the in-app updater (T073) and `brew upgrade` would both try to own.

**Why it is generated.** The version, archive and checksum are read from the
manifest the release host serves, after its Ed25519 signature is checked
against the key this repository ships (`keys/release.pub`) — so a formula can
only ever point at an archive the release key signed. Hand-editing three values
that must agree with a published file is how a formula ends up installing a
checksum mismatch.

    python scripts/homebrew.py                 # from the live manifest
    python scripts/homebrew.py --manifest m.json --url https://host/latest.json
    python scripts/homebrew.py --check         # fail if the file is stale
"""

from __future__ import annotations

import argparse
import json
import re
import sys
import urllib.request
from pathlib import Path
from urllib.parse import urljoin, urlparse

ROOT = Path(__file__).resolve().parents[1]
FORMULA = ROOT / "packaging" / "homebrew" / "Formula" / "throughline.rb"
MANIFEST_URL = "https://throughline-research.pages.dev/latest.json"
HOMEPAGE = "https://throughline-research.pages.dev"
USER_AGENT = "Throughline-Installer (+https://throughline-research.pages.dev)"

VERSION = re.compile(r"^v(\d+)\.(\d+)\.(\d+)$")
SHA256 = re.compile(r"^[0-9a-f]{64}$")


class FormulaError(RuntimeError):
    """The manifest cannot be turned into a formula, for a reason worth reading."""


def fetch(url: str) -> dict:
    request = urllib.request.Request(url, headers={"User-Agent": USER_AGENT})
    with urllib.request.urlopen(request, timeout=60) as response:
        return json.load(response)


def verified(manifest: dict) -> dict:
    """The manifest, if the release key signed it; otherwise refuse."""
    sys.path.insert(0, str(ROOT / "packages" / "research-domain" / "src"))
    from throughline_domain import signing

    key = signing.public_key(ROOT)
    if not key:
        raise FormulaError("keys/release.pub is missing, so the manifest cannot be checked.")
    try:
        signing.verify(manifest, key)
    except signing.VerificationError as error:
        raise FormulaError(f"The manifest did not verify: {error}") from error
    return manifest


def archive_url(manifest: dict, manifest_url: str) -> tuple[str, str, str]:
    """Version, archive URL and checksum, each checked for shape."""
    version = str(manifest.get("version", ""))
    name = str(manifest.get("file", ""))
    digest = str(manifest.get("sha256", "")).lower()
    if not VERSION.match(version):
        raise FormulaError(f"{version!r} is not a release version like v1.2.3.")
    if name != f"throughline-{version}.tar.gz":
        # Pinned to the name the release builder writes, so the formula can
        # never be pointed at a path — or at a mutable name like latest.tar.gz,
        # whose checksum would break the formula the next time it changed.
        raise FormulaError(f"{name!r} is not the archive name for {version}.")
    if not SHA256.match(digest):
        raise FormulaError("The manifest's sha256 is not a SHA-256 digest.")
    url = urljoin(manifest_url, name)
    if urlparse(url).scheme != "https":
        raise FormulaError(f"{url} is not served over HTTPS.")
    return version, url, digest


def render(version: str, url: str, digest: str) -> str:
    """The formula, in the form `brew style` accepts."""
    return f'''# Generated by scripts/homebrew.py from the signed release manifest ({version}).
# Do not edit by hand: regenerate, so the archive and checksum always match a
# release the Throughline release key signed.
class Throughline < Formula
  desc "Local-first research workspace that tests claims against data"
  homepage "{HOMEPAGE}"
  url "{url}"
  sha256 "{digest}"
  license "Apache-2.0"

  # Any Python 3.8+ starts the installer, which then fetches the exact runtime
  # Throughline pins. A Mac's /usr/bin/python3 is only a stub until the command
  # line tools are installed, so the formula brings one.
  depends_on "python@3.12"

  def install
    libexec.install "scripts/install.sh"
    (bin/"throughline").write_env_script libexec/"install.sh",
      PATH: "#{{formula_opt_libexec("python@3.12")}}/bin:$PATH"
  end

  def caveats
    <<~EOS
      Run `throughline` to set Throughline up in ~/throughline-os and start it.
      After that the same command starts it, and says when a newer release
      is published.

      Your research data lives in ~/.throughline-os. `brew uninstall` removes
      only the `throughline` command; it never touches your data.
    EOS
  end

  test do
    # The launcher itself, parsed but not run: running it would install the
    # whole program into the test's home.
    system "sh", "-n", libexec/"install.sh"
    assert_path_exists bin/"throughline"
  end
end
'''


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("--url", default=MANIFEST_URL,
                        help="the manifest's URL, which archive names are resolved against")
    parser.add_argument("--manifest", type=Path,
                        help="read the manifest from this file instead of fetching --url")
    parser.add_argument("--out", type=Path, default=FORMULA)
    parser.add_argument("--check", action="store_true",
                        help="exit 1 if the formula on disk differs from the manifest")
    args = parser.parse_args(argv)

    try:
        manifest = (json.loads(args.manifest.read_text()) if args.manifest
                    else fetch(args.url))
        version, url, digest = archive_url(verified(manifest), args.url)
    except (FormulaError, OSError, ValueError) as error:
        print(f"homebrew: {error}", file=sys.stderr)
        return 1

    text = render(version, url, digest)
    if args.check:
        current = args.out.read_text() if args.out.exists() else ""
        if current != text:
            print(f"homebrew: {args.out} does not match {version}; regenerate it.",
                  file=sys.stderr)
            return 1
        print(f"homebrew: {args.out} matches {version}.")
        return 0
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(text)
    print(f"homebrew: wrote {args.out} for {version}.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
