# Generated by scripts/homebrew.py from the signed release manifest (v0.3.0).
# Do not edit by hand: regenerate, so the archive and checksum always match a
# release the Throughline release key signed.
class Throughline < Formula
  desc "Local-first research workspace that tests claims against data"
  homepage "https://throughline-research.pages.dev"
  url "https://throughline-research.pages.dev/throughline-v0.3.0.tar.gz"
  sha256 "d2716882fea985eec6caabdcef2351022fa0bb1b317da7e53ecf9dde05c140e7"
  license "Apache-2.0"

  # Any Python 3.8+ starts the installer, which then fetches the exact runtime
  # Throughline pins. A Mac's /usr/bin/python3 is only a stub until the command
  # line tools are installed, so the formula brings one.
  depends_on "python@3.12"

  def install
    libexec.install "scripts/install.sh"
    (bin/"throughline").write_env_script libexec/"install.sh",
      PATH: "#{formula_opt_libexec("python@3.12")}/bin:$PATH"
  end

  def caveats
    <<~EOS
      Run `throughline` to set Throughline up in ~/throughline-os and start it.
      After that the same command starts it, and says when a newer release
      is published.

      Your research data lives in ~/.throughline-os. `brew uninstall` removes
      only the `throughline` command; it never touches your data.
    EOS
  end

  test do
    # The launcher itself, parsed but not run: running it would install the
    # whole program into the test's home.
    system "sh", "-n", libexec/"install.sh"
    assert_path_exists bin/"throughline"
  end
end
